name: Deploy to Lightsail

on:
  push:
    branches: ["api-light"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "mkdir -p ~/app"
          rsync -avz --delete --exclude='.git' --exclude='docker-compose.override.yml ./ ubuntu@${{ secrets.SERVER_IP }}:~/app/

      - name: Rebuild and restart containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/app
            GF_SECURITY_ADMIN_USER="${GF_SECURITY_ADMIN_USER}" \
            GF_SECURITY_ADMIN_PASSWORD="${GF_SECURITY_ADMIN_PASSWORD}" \
            docker compose -p bg_remover up -d --build --no-deps up
          EOF
        env:
          GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
